security:
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        main:
            anonymous : true
            # http_basic : true
            guard:
                authenticators:
                    - App\Security\FormulaireLoginAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            # form_login : true

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 10

    access_control:
        - { path: ^/ajoutEntreprise, roles: ROLE_ADMIN }
        - { path: ^/ajoutStage, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
